#!/bin/bash

# usage: create-dmg [32-bit-p]
# if 32-bit-p is non-blank, will install the 32-bit image.
# otherwise, installs the 64-bit image.

# This script expects to be run from its directory.
# Copy InfoPlist.strings from this dir and the Truledger binary
# from the parent dir into the Truledger.app in Truledger.sparseimage,
# and convert that to a compressed Truledger.dmg.

# Edit InfoPlist.strings before running this, changing the version
# numbers and copyright year to match your binary.

# This will fail if you don't have admin privileges on your machine.

# Usually, this script is run automatically by .../truledger/truledger-app

THREETWOP=$1
IMAGE=truledger-dx86cl64
SUFFIX=''

if [[ "x$THREETWOP" != "x" ]]; then
    IMAGE=truledger-dx86cl
    SUFFIX='-32'
fi

if [ -f ../$IMAGE ]; then
  echo "Building Truledger$SUFFIX.dmg with $IMAGE";
else
  echo "Can't find $IMAGE"
  exit
fi

hdiutil detach /Volumes/Truledger 2>/dev/null
hdiutil detach /Volumes/Truledger\ 1 2>/dev/null
gunzip -c Truledger.sparseimage.gz >Truledger-copy.sparseimage
hdiutil attach Truledger-copy.sparseimage
cp InfoPlist.strings ../$IMAGE /Volumes/Truledger/Truledger.app/Contents/Resources/
hdiutil detach /Volumes/Truledger
rm -f Truledger.dmg
hdiutil convert Truledger-copy.sparseimage -format UDZO -o Truledger$SUFFIX.dmg
hdiutil detach /Volumes/Truledger 2>/dev/null
hdiutil detach /Volumes/Truledger\ 1 2>/dev/null
rm Truledger-copy.sparseimage
