#!/bin/bash
# Push the HEAD to the shared repository
# assumes the following remotes:
# git remote add truledger git+ssh://$HUBTL/usr/local/www/truledger/repos/truledger.git
# git remote add origin git@github.com:billstclair/truledger.git

# get the current branch, "git branch --contains" outputs "* branch"
branch=`git branch --contains`
branch=${branch:2}

echo "Pushing branch: $branch"
git push origin $branch
git push truledger $branch

# public access:
# git remote add github git://github.com/billstclair/truledger.git
