#!/bin/bash
# Push the HEAD to the shared repository
# assumes the following remotes:
# git remote add truledger git+ssh://$HUBTL/usr/local/www/truledger/repos/truledger.git
# git remote add github git@github.com:billstclair/truledger.git
git push --tags truledger master
git push --tags github master

# useful for public access
# git remote add github git://github.com/billstclair/truledger.git
