#!/bin/bash
# Load Truledger and save-application
rm src/*.*fsl                   # Force recompile
ccl -e '(load "truledger-loader.lisp")' \
    -e '(when (find-package :truledger) (in-package :truledger))' \
    -e '(write-application-name "appname.txt")' \
    -e '(truledger:save-truledger-application)'
APPNAME=`cat appname.txt`
tar -czf $APPNAME.tar.gz $APPNAME
echo $APPNAME packaged as $APPNAME.tar.gz
