#!/bin/bash
# Usage is: "truledger [slimeport]"

# For submodules in systems/
git submodule init
git submodule update

if [ "x$CCL" = 'x' ]; then
  CCL=ccl
fi
$CCL -R 200M \
     -e '(load "start")' \
     -e '(when (find-package :truledger) (in-package :truledger))' \
     -e "(cl-user::start-swank $1)"
