#!/bin/bash
# Load Truledger and save-application
# Create installer

NODEB=$1
VERSION=`cat VERSION`

if [[ "x$CCL" == 'x' ]]; then
  CCL=ccl
fi
$CCL -e '(load "start")' \
     -e '(when (find-package :truledger) (in-package :truledger))' \
     -e '(write-application-name "appname.txt")' \
     -e '(truledger:save-truledger-application)'
APPNAME=`cat appname.txt`
tar -czf $APPNAME.tar.gz $APPNAME
echo $APPNAME packaged as $APPNAME.tar.gz

if [[ x$NODEB == x ]]; then
  BITS=64
  if [[ `uname -s` == 'Darwin' ]]; then
    if [[ $APPNAME == 'truledger-dx86cl' ]]; then BITS=32; fi
    cd appmac
    ./create-dmg $VERSION $BITS
  elif [[ `uname -s` == 'Linux' ]]; then
    if [ -x "`which dpkg 2>/dev/null`" ]; then
      if [[ $APPNAME == 'truledger-lx86cl' ]]; then BITS=32; fi
      cd applin
      ./create-deb $VERSION $BITS
    fi
  fi
fi
