#!/bin/bash
# Load Truledger and save-application
# Create installer

if [[ "x$CCL" == 'x' ]]; then
  CCL=ccl
fi
$CCL -e '(load "start")' \
     -e '(when (find-package :truledger) (in-package :truledger))' \
     -e '(write-application-name "appname.txt")' \
     -e '(truledger:save-truledger-application)'
APPNAME=`cat appname.txt`
tar -czf $APPNAME.tar.gz $APPNAME
echo $APPNAME packaged as $APPNAME.tar.gz
if [[ `uname -s` == 'Darwin' ]]; then
  THREETWO=''
  if [[ $APPNAME == 'truledger-dx86cl' ]]; then THREETWO='y'; fi
  cd appmac
  ./create-dmg $THREETWO
fi
