#!/bin/bash
# Usage is: "truledger [slimeport]"
if [ "x$CCL" = 'x' ]; then
  $CCL=ccl
fi
rm src/*.*fsl                   # Force recompile
$CCL -e '(load "truledger-loader.lisp")' \
     -e '(when (find-package :truledger) (in-package :truledger))' \
     -e "(truledger-loader:load-swank $1)"
