; -*- mode: lisp -*-

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; tokenize the protocol strings
;;;

(in-package :trubanc)

;; db file & directory names
(defconstant $TIME "time")
(defconstant $kTIME :|time|)
(defconstant $PRIVKEY "privkey")
(defconstant $kPRIVKEY :|privkey|)
(defconstant $BANKID "bankid")
(defconstant $kBANKID :|bankid|)
(defconstant $TOKENID "tokenid")
(defconstant $kTOKENID :|tokenid|)
(defconstant $REGFEE "regfee")
(defconstant $kREGFEE :|regfee|)
(defconstant $TRANFEE "tranfee")
(defconstant $kTRANFEE :|tranfee|)
(defconstant $FEE "fee")
(defconstant $kFEE :|fee|)
(defconstant $PUBKEY "pubkey")
(defconstant $kPUBKEY :|pubkey|)
(defconstant $PUBKEYSIG "pubkeysig")
(defconstant $kPUBKEYSIG :|pubkeysig|)
(defconstant $ASSET "asset")
(defconstant $kASSET :|asset|)
(defconstant $STORAGE "storage")
(defconstant $kSTORAGE :|storage|)
(defconstant $STORAGEFEE "storagefee")
(defconstant $kSTORAGEFEE :|storagefee|)
(defconstant $FRACTION "fraction")
(defconstant $kFRACTION :|fraction|)
(defconstant $ACCOUNT "account")
(defconstant $kACCOUNT :|account|)
(defconstant $LAST "last")
(defconstant $kLAST :|last|)
(defconstant $REQ "req")
(defconstant $kREQ :|req|)
(defconstant $BALANCE "balance")
(defconstant $kBALANCE :|balance|)
(defconstant $MAIN "main")
(defconstant $kMAIN :|main|)
(defconstant $OUTBOX "outbox")
(defconstant $kOUTBOX :|outbox|)
(defconstant $OUTBOXHASH "outboxhash")
(defconstant $kOUTBOXHASH :|outboxhash|)
(defconstant $INBOX "inbox")
(defconstant $kINBOX :|inbox|)
(defconstant $COUPON "coupon")
(defconstant $kCOUPON :|coupon|)

;; request names
(defconstant $ID "id")
(defconstant $kID :|id|)
(defconstant $REGISTER "register")
(defconstant $kREGISTER :|register|)
(defconstant $FAILED "failed")
(defconstant $kFAILED :|failed|)
(defconstant $REASON "reason")
(defconstant $kREASON :|reason|)
(defconstant $GETREQ "getreq")
(defconstant $kGETREQ :|getreq|)
(defconstant $GETTIME "gettime")
(defconstant $kGETTIME :|gettime|)
(defconstant $GETFEES "getfees")
(defconstant $kGETFEES :|getfees|)
(defconstant $SPEND "spend")
(defconstant $kSPEND :|spend|)
(defconstant $GETINBOX "getinbox")
(defconstant $kGETINBOX :|getinbox|)
(defconstant $PROCESSINBOX "processinbox")
(defconstant $kPROCESSINBOX :|processinbox|)
(defconstant $STORAGEFEES "storagefees")
(defconstant $kSTORAGEFEES :|storagefees|)
(defconstant $SPENDACCEPT "spend|accept")
(defconstant $kSPENDACCEPT :|spend\|accept|)
(defconstant $SPENDREJECT "spend|reject")
(defconstant $kSPENDREJECT :|spend\|reject|)
(defconstant $AFFIRM "affirm")
(defconstant $kAFFIRM :|affirm|)
(defconstant $GETASSET "getasset")
(defconstant $kGETASSET :|getasset|)
(defconstant $GETOUTBOX "getoutbox")
(defconstant $kGETOUTBOX :|getoutbox|)
(defconstant $GETBALANCE "getbalance")
(defconstant $kGETBALANCE :|getbalance|)
(defconstant $COUPONENVELOPE "couponenvelope")
(defconstant $kCOUPONENVELOPE :|couponenvelope|)

;; Affirmations
(defconstant $ATREGISTER "@register")
(defconstant $kATREGISTER :|@register|)
(defconstant $ATOUTBOXHASH "@outboxhash")
(defconstant $kATOUTBOXHASH :|@outboxhash|)
(defconstant $ATSTORAGE "@storage")
(defconstant $kATSTORAGE :|@storage|)
(defconstant $ATSTORAGEFEE "@storagefee")
(defconstant $kATSTORAGEFEE :|@storagefee|)
(defconstant $ATFRACTION "@fraction")
(defconstant $kATFRACTION :|@fraction|)
(defconstant $ATBALANCE "@balance")
(defconstant $kATBALANCE :|@balance|)
(defconstant $ATSPEND "@spend")
(defconstant $kATSPEND :|@spend|)
(defconstant $ATTRANFEE "@tranfee")
(defconstant $kATTRANFEE :|@tranfee|)
(defconstant $ATASSET "@asset")
(defconstant $kATASSET :|@asset|)
(defconstant $ATGETINBOX "@getinbox")
(defconstant $kATGETINBOX :|@getinbox|)
(defconstant $ATPROCESSINBOX "@processinbox")
(defconstant $kATPROCESSINBOX :|@processinbox|)
(defconstant $ATSTORAGEFEES "atstoragefees")
(defconstant $kATSTORAGEFEES :|atstoragefees|)
(defconstant $ATSPENDACCEPT "@spend|accept")
(defconstant $kATSPENDACCEPT :|@spend\|accept|)
(defconstant $ATSPENDREJECT "@spend|reject")
(defconstant $kATSPENDREJECT :|@spend\|reject|)
(defconstant $ATGETOUTBOX "@getoutbox")
(defconstant $kATGETOUTBOX :|@getoutbox|)
(defconstant $ATBALANCEHASH "@balancehash")
(defconstant $kATBALANCEHASH :|@balancehash|)
(defconstant $ATCOUPON "@coupon")
(defconstant $kATCOUPON :|@coupon|)
(defconstant $ATCOUPONENVELOPE "@couponenvelope")
(defconstant $kATCOUPONENVELOPE :|@couponenvelope|)

;; request parameter names
(defconstant $CUSTOMER "customer")
(defconstant $kCUSTOMER :|customer|)
(defconstant $REQUEST "request")
(defconstant $kREQUEST :|request|)
(defconstant $NAME "name")
(defconstant $kNAME :|name|)
(defconstant $NOTE "note")
(defconstant $kNOTE :|note|)
(defconstant $ACCT "acct")
(defconstant $kACCT :|acct|)
(defconstant $OPERATION "operation")
(defconstant $kOPERATION :|operation|)
(defconstant $TRAN "tran")
(defconstant $kTRAN :|tran|)
(defconstant $AMOUNT "amount")
(defconstant $kAMOUNT :|amount|)
(defconstant $ASSETNAME "assetname")
(defconstant $kASSETNAME :|assetname|)
(defconstant $SCALE "scale")
(defconstant $kSCALE :|scale|)
(defconstant $PRECISION "precision")
(defconstant $kPRECISION :|precision|)
(defconstant $PERCENT "percent")
(defconstant $kPERCENT :|percent|)
(defconstant $TIMELIST "timelist")
(defconstant $kTIMELIST :|timelist|)
(defconstant $HASH "hash")
(defconstant $kHASH :|hash|)
(defconstant $MSG "msg")
(defconstant $kMSG :|msg|)
(defconstant $ERRMSG "errmsg")
(defconstant $kERRMSG :|errmsg|)
(defconstant $BALANCEHASH "balancehash")
(defconstant $kBALANCEHASH :|balancehash|)
(defconstant $COUNT "count")
(defconstant $kCOUNT :|count|)
(defconstant $BANKURL "bankurl")
(defconstant $kBANKURL :|bankurl|)
(defconstant $ENCRYPTEDCOUPON "encryptedcoupon")
(defconstant $kENCRYPTEDCOUPON :|encryptedcoupon|)
(defconstant $COUPONNUMBERHASH "couponnumberhash")
(defconstant $kCOUPONNUMBERHASH :|couponnumberhash|)
(defconstant $ISSUER "issuer")
(defconstant $kISSUER :|issuer|)

;; Client database keys
(defconstant $BANK "bank")
(defconstant $kBANK :|bank|)
(defconstant $URL "url")
(defconstant $kURL :|url|)
(defconstant $NICKNAME "nickname")
(defconstant $kNICKNAME :|nickname|)
(defconstant $CONTACT "contact")
(defconstant $kCONTACT :|contact|)
(defconstant $SESSION "session")
(defconstant $kSESSION :|session|)
(defconstant $PREFERENCE "preference")
(defconstant $kPREFERENCE :|preference|)
(defconstant $TOKEN "token")
(defconstant $kTOKEN :|token|)
(defconstant $HISTORY "history")
(defconstant $kHISTORY :|history|)

;; Other client tokens
(defconstant $FORMATTEDAMOUNT "formattedamount")
(defconstant $kFORMATTEDAMOUNT :|formattedamount|)
(defconstant $MSGTIME "msgtime")
(defconstant $kMSGTIME :|msgtime|)
(defconstant $ATREQUEST "@request")
(defconstant $kATREQUEST :|@request|)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Copyright 2009 Bill St. Clair
;;;
;;; Licensed under the Apache License, Version 2.0 (the "License");
;;; you may not use this file except in compliance with the License.
;;; You may obtain a copy of the License at
;;;
;;;     http://www.apache.org/licenses/LICENSE-2.0
;;;
;;; Unless required by applicable law or agreed to in writing, software
;;; distributed under the License is distributed on an "AS IS" BASIS,
;;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;;; See the License for the specific language governing permissions
;;; and limitations under the License.
;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
